// apps/bot/src/services/pdfkit-report.ts
import PDFDocument from "pdfkit";
import dayjs from "dayjs";

export type FeedbackShape = {
  telegramId: string | number;
  subjectLabel: string;
  score?: number;          // 0..100
  gradeText?: string;      // e.g., "B+"
  weakTopics?: string[];
  remarks?: string;
  startedAt?: string;      // ISO
  finishedAt?: string;     // ISO
  plan?: "free" | "lite" | "steady" | "serious" | "elite" | "limited";
};

export async function buildFeedbackPDF(fb: FeedbackShape): Promise<Buffer> {
  // ---- normalize / guard inputs
  const subject = safeText(fb.subjectLabel) || "—";
  const score = clamp(Math.round(Number(fb.score ?? 0)), 0, 100);
  const grade = safeText(fb.gradeText) || "—";
  const plan = (fb.plan ?? "free") as string;

  const started = parseISO(fb.startedAt);
  const finished = parseISO(fb.finishedAt);
  const dateLabel = dayjs(finished ?? started ?? new Date()).format("YYYY-MM-DD HH:mm");

  const topics = Array.isArray(fb.weakTopics) && fb.weakTopics.length
    ? fb.weakTopics.map(safeText).filter(Boolean)
    : ["None detected"];

  const remarks = safeText(fb.remarks) || "—";

  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 56, bottom: 56, left: 56, right: 56 },
    autoFirstPage: true,
  });

  const chunks: Buffer[] = [];

  // page numbers (current only; total is expensive without a 2-pass render)
  let pageNo = 0;
  const drawFooter = () => {
    pageNo += 1;
    doc.fontSize(9).fillColor("#888888");
    const footer = `Page ${pageNo}`;
    doc.text(footer, doc.page.margins.left, doc.page.height - doc.page.margins.bottom + 24, {
      width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
      align: "center",
    });
  };
  doc.on("pageAdded", drawFooter);

  return new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (buf) => chunks.push(buf));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ============ Header ============ //
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .fillColor("#111111")
      .text("BrainBot KCSE Report", { align: "left" })
      .moveDown(0.4);

    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#666666")
      .text(`Date: ${dateLabel}`)
      .text(`Student: ${String(fb.telegramId)}`)
      .text(`Plan: ${plan}`)
      .moveDown(0.8);

    // ============ Info band ============ //
    drawInfoBand(doc, {
      subject,
      score,
      grade,
      duration: started && finished ? humanDuration(dayjs(started), dayjs(finished)) : "—",
    });

    doc.moveDown(1.2);

    // ============ Weak topics ============ //
    drawSectionTitle(doc, "Weak Topics");
    doc.moveDown(0.25);
    doc.font("Helvetica").fontSize(11).fillColor("#222222");

    // show up to 12 topics, then “+N more…”
    const MAX_TOPICS = 12;
    const visible = topics.slice(0, MAX_TOPICS);
    for (const t of visible) doc.text(`• ${t}`, { width: contentWidth(doc) });
    if (topics.length > MAX_TOPICS) {
      doc.fillColor("#666666").text(`+${topics.length - MAX_TOPICS} more…`);
      doc.fillColor("#222222");
    }

    doc.moveDown(0.8);

    // ============ Examiner remarks ============ //
    drawSectionTitle(doc, "Examiner Notes");
    doc.moveDown(0.25);
    doc.font("Helvetica").fontSize(11).fillColor("#222222");
    doc.text(remarks, {
      width: contentWidth(doc),
      lineGap: 2,
    });

    // ============ Footer tagline ============ //
    doc.moveDown(1.6);
    doc
      .fontSize(9)
      .fillColor("#888888")
      .text(
        "Generated by BrainBot • KCSE prep with analytics and examiner-style feedback.",
        { align: "center" }
      );

    // draw footer for the last page (first page doesn’t emit pageAdded beforehand)
    drawFooter();

    doc.end();
  });
}

/* ================= helpers ================= */

function safeText(v: unknown): string {
  const s = typeof v === "string" ? v : v == null ? "" : String(v);
  // collapse whitespace; PDFKit handles wrapping, but avoid weird control chars
  return s.replace(/\s+/g, " ").trim().slice(0, 5000);
}

function clamp(n: number, lo: number, hi: number) {
  return Math.min(hi, Math.max(lo, n));
}

function parseISO(v?: string) {
  if (!v) return undefined;
  const d = new Date(v);
  return isNaN(d.getTime()) ? undefined : d;
}

function contentWidth(doc: PDFKit.PDFDocument) {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

function drawSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.fillColor("#111111").font("Helvetica-Bold").fontSize(16).text(title);
}

function drawInfoBand(
  doc: PDFKit.PDFDocument,
  data: { subject: string; score: number; grade: string; duration: string }
) {
  const w = contentWidth(doc);
  const h = 72;
  const r = 12;
  const x = doc.page.margins.left;
  const y = doc.y;

  doc
    .roundedRect(x, y, w, h, r)
    .fill("#F5F7FA");

  const padX = x + 16;
  const padY = y + 12;

  doc.fillColor("#111111").fontSize(13).font("Helvetica-Bold");
  doc.text("Subject", padX, padY);
  doc.font("Helvetica").text(data.subject, padX, padY + 18, { width: 180 });

  doc.font("Helvetica-Bold").text("Score", padX + 210, padY);
  doc.font("Helvetica").text(`${data.score}/100 (${data.grade})`, padX + 210, padY + 18, { width: 140 });

  doc.font("Helvetica-Bold").text("Duration", padX + 390, padY);
  doc.font("Helvetica").text(data.duration, padX + 390, padY + 18, { width: 120 });

  // restore cursor just below the band
  doc.y = y + h + 8;
}

function humanDuration(start: dayjs.Dayjs, end: dayjs.Dayjs) {
  const ms = Math.max(0, end.diff(start));
  const mins = Math.round(ms / 60000);
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h ? `${h}h ${m}m` : `${m}m`;
}
