// apps/bot/src/services/pdfkit-report.ts
import PDFDocument from "pdfkit";
import dayjs from "dayjs";

export type FeedbackShape = {
  telegramId: string | number;
  subjectLabel: string;
  score?: number;          // 0..100
  gradeText?: string;      // e.g., "B+"
  weakTopics?: string[];
  remarks?: string;
  startedAt?: string;      // ISO
  finishedAt?: string;     // ISO
  plan?: "free" | "lite" | "steady" | "serious" | "elite";
};

export async function buildFeedbackPDF(fb: FeedbackShape): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margins: { top: 56, bottom: 56, left: 56, right: 56 } });

  const chunks: Buffer[] = [];
  return new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (buf) => chunks.push(buf));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .fillColor("#111111")
      .text("BrainBot KCSE Report", { align: "left" })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#666666")
      .text(`Date: ${dayjs(fb.finishedAt || new Date()).format("YYYY-MM-DD HH:mm")}`)
      .text(`Student: ${fb.telegramId}`)
      .text(`Plan: ${fb.plan ?? "free"}`)
      .moveDown(1.0);

    // Info band
    doc
      .roundedRect(doc.x, doc.y, doc.page.width - doc.page.margins.left - doc.page.margins.right, 70, 12)
      .fill("#F5F7FA");
    doc.fillColor("#111111").fontSize(14).font("Helvetica-Bold");
    const yBase = doc.y + 12;
    const x = doc.x + 16;
    doc.text("Subject", x, yBase);
    doc.font("Helvetica").text(fb.subjectLabel || "—", x, yBase + 18);

    doc.font("Helvetica-Bold").text("Score", x + 220, yBase);
    doc.font("Helvetica").text(`${fb.score ?? 0}/100 (${fb.gradeText ?? "—"})`, x + 220, yBase + 18);

    doc.font("Helvetica-Bold").text("Duration", x + 380, yBase);
    const dur =
      fb.startedAt && fb.finishedAt
        ? humanDuration(dayjs(fb.startedAt), dayjs(fb.finishedAt))
        : "—";
    doc.font("Helvetica").text(dur, x + 380, yBase + 18);

    doc.moveDown(1.8);

    // Weak topics
    doc.fillColor("#111111").fontSize(16).font("Helvetica-Bold").text("Weak Topics");
    doc.moveDown(0.4);
    doc.fontSize(11).font("Helvetica").fillColor("#222222");
    const topics = fb.weakTopics?.length ? fb.weakTopics : ["None detected"];
    topics.forEach((t) => doc.text(`• ${t}`));
    doc.moveDown(1.0);

    // Examiner remarks
    doc.fillColor("#111111").fontSize(16).font("Helvetica-Bold").text("Examiner Notes");
    doc.moveDown(0.4);
    doc.fontSize(11).font("Helvetica").fillColor("#222222");
    doc.text(fb.remarks || "—");

    // Footer
    doc.moveDown(2);
    doc.fontSize(9).fillColor("#888888").text("Generated by BrainBot • KCSE prep with analytics and examiner-style feedback.", {
      align: "center",
    });

    doc.end();
  });
}

function humanDuration(start: dayjs.Dayjs, end: dayjs.Dayjs) {
  const ms = Math.max(0, end.diff(start));
  const mins = Math.round(ms / 60000);
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h ? `${h}h ${m}m` : `${m}m`;
}
